### ISSUE TITLE
一个AI产品数据怎么添加到数据库，能否给个说明。

### ISSUE THREAD

**Issue by cced3000** [DiscovAI/DiscovAI-search#1]
因为没办法可视化添加数据，所以想了解一下 一个AI产品数据，怎么入库到 aitools 和 aitools_chunk，前者比较清晰，后者对应的数据应该怎么添加，不是太理解。

**Comment by Ryan-yang125** [comment]
需要将数据 split 成 多个chunks，然后向量化，再插入 aitools_chunk 中。
后端部分代码我也正在开源成一个爬虫服务 ，就可以通过 ui一键添加网站到数据库中，还有部分逻辑没有完成，不过可以先参考下这里向量化的代码https://github.com/DiscovAI/DiscovAI-crawl/blob/main/src/service/embedding.ts
DiscovAI-crawl这部分完成后 会提供更详细的文档
